import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import matter from 'gray-matter';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const COURSES_DIR = path.join(__dirname, 'courses');
const OUTPUT_FILE = path.join(__dirname, 'scripts', 'courses-data.js');

function scanCourses() {
    const courses = [];

    if (!fs.existsSync(COURSES_DIR)) {
        fs.mkdirSync(COURSES_DIR, { recursive: true });
        return courses;
    }

    const courseFolders = fs.readdirSync(COURSES_DIR).filter(name => {
        return fs.statSync(path.join(COURSES_DIR, name)).isDirectory();
    });

    for (const folder of courseFolders) {
        const coursePath = path.join(COURSES_DIR, folder);
        const outlinePath = path.join(coursePath, 'outline.md');

        let courseData = {
            slug: folder,
            title: folder,
            description: '',
            lessons: []
        };

        if (fs.existsSync(outlinePath)) {
            const content = fs.readFileSync(outlinePath, 'utf-8');
            const parsed = matter(content);
            courseData.title = parsed.data.title || folder;
            courseData.description = parsed.data.description || '';
        }

        const lessonFolders = fs.readdirSync(coursePath).filter(name => {
            return fs.statSync(path.join(coursePath, name)).isDirectory();
        });

        for (const lessonFolder of lessonFolders) {
            const lessonPath = path.join(coursePath, lessonFolder);
            const lessonOutlinePath = path.join(lessonPath, 'outline.md');
            const lessonMetaPath = path.join(lessonPath, 'meta.json');

            let lessonData = {
                slug: lessonFolder,
                title: lessonFolder,
                description: '',
                hasOutline: fs.existsSync(lessonOutlinePath),
                hasMeta: fs.existsSync(lessonMetaPath)
            };

            if (fs.existsSync(lessonOutlinePath)) {
                const content = fs.readFileSync(lessonOutlinePath, 'utf-8');
                const parsed = matter(content);
                lessonData.title = parsed.data.title || lessonFolder;
                lessonData.description = parsed.data.description || '';
            }

            courseData.lessons.push(lessonData);
        }

        courses.push(courseData);
    }

    return courses;
}

function generateCoursesData() {
    const courses = scanCourses();
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }
    const jsContent = `// Auto-generated by build.js
const COURSES_DATA = ${JSON.stringify(courses, null, 2)};
export default COURSES_DATA;
`;
    fs.writeFileSync(OUTPUT_FILE, jsContent, 'utf-8');
    console.log(`Generated ${OUTPUT_FILE} with ${courses.length} courses`);
}

generateCoursesData();