// Auto-generated by build.js
const COURSES_DATA = [
  {
    "slug": "02-Scratch初阶",
    "title": "02-Scratch初阶",
    "description": "",
    "lessons": [
      {
        "slug": "00-海底世界",
        "title": "00-海底世界",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "04-猜数字",
        "title": "04-猜数字",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      }
    ]
  },
  {
    "slug": "03-cpp语法基础",
    "title": "03-cpp语法基础",
    "description": "",
    "lessons": [
      {
        "slug": "01-简单程序设计",
        "title": "01-简单程序设计",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      }
    ]
  },
  {
    "slug": "C++语法篇",
    "title": "C++语法篇",
    "description": "",
    "lessons": [
      {
        "slug": "01-算术表达式",
        "title": "01-算术表达式",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "02-变量及其输入",
        "title": "02-变量及其输入",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "03-顺序结构程序设计",
        "title": "03-顺序结构程序设计",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "04-分支结构程序设计",
        "title": "04-分支结构程序设计",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      }
    ]
  },
  {
    "slug": "Python语法篇",
    "title": "Python语法篇",
    "description": "",
    "lessons": [
      {
        "slug": "01-算术表达式",
        "title": "01-算术表达式",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "02-变量及其输入",
        "title": "02-变量及其输入",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "03-顺序结构程序设计",
        "title": "03-顺序结构程序设计",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "04-分支结构程序设计",
        "title": "04-分支结构程序设计",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      }
    ]
  },
  {
    "slug": "练习小项目",
    "title": "Python入门",
    "description": "从零开始学习Python基础语法",
    "lessons": [
      {
        "slug": "00-Python导学",
        "title": "00-Python导学",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "凯撒密码",
        "title": "凯撒密码",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      }
    ]
  }
];
export default COURSES_DATA;
