// Auto-generated by build.js
const COURSES_DATA = [
  {
    "slug": "01-Python入门",
    "title": "Python入门",
    "description": "从零开始学习Python基础语法",
    "lessons": [
      {
        "slug": "01-变量与类型",
        "title": "01-变量与类型",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      }
    ]
  },
  {
    "slug": "02-HTML与CSS入门",
    "title": "HTML与CSS入门",
    "description": "学习网页结构与样式设计",
    "lessons": [
      {
        "slug": "01-认识HTML",
        "title": "01-认识HTML",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "02-常用标签",
        "title": "02-常用标签",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      },
      {
        "slug": "03-CSS基础",
        "title": "03-CSS基础",
        "description": "",
        "hasOutline": false,
        "hasMeta": false
      }
    ]
  }
];
export default COURSES_DATA;
